name: ksoc-guard

on: [push]

jobs:
  ksoc-guard:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: KSOC Guard
        uses: ksoclabs/guard-action@sarif-support
        with:
          policy_dir: /policies
          fail_on_severity: none
          format: sarif
