name: ksoc-image-scan

on: [push]

jobs:
  ksoc-image-scan:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: build local container
        uses: docker/build-push-action@v4
        with:
          tags: localbuild/testimage:latest
          push: false
          load: true
      - name: KSOC Image Scan
        uses: ksoclabs/image-scan-action@v0.0.4
        id: scan
        with:
          image: localbuild/testimage:latest
          format: sarif
      - name: Upload Image Scan SARIF Report
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
